CREATE TABLE PEDIDOS(NROPEDIDO INTEGER CONSTRAINT PK_PEDIDOS PRIMARY KEY,
                     DATA DATE CONSTRAINT NNDATA NOT NULL,
                     CODCLIENTE INTEGER CONSTRAINT NNCOD_CLIENTE NOT NULL,
                     SITUACAO INTEGER CONSTRAINT NNSITUACAO NOT NULL,
                     DATAENTREGA DATE CONSTRAINT NNDATAENTRGA NOT NULL,
                     CODCPAGTO INTEGER CONSTRAINT NNCODCPAGTO NOT NULL,
                     CODFORMAPAGTO INTEGER,
                     QTDETOTAL NUMERIC(10,2) CONSTRAINT NNQTDETOTAL NOT NULL,
                     VALORTOTAL NUMERIC(10,2),
                     TIPO VARCHAR (1) CONSTRAINT NNTIPO NOT NULL,
                     OBS VARCHAR (255));
                     
ALTER TABLE PEDIDOS
ADD FOREIGN KEY (CODCLIENTE) REFERENCES CLIENTES(CODCLIENTE);

ALTER TABLE PEDIDOS
ADD FOREIGN KEY (CODCPAGTO) REFERENCES CPAGTO(CODCPAGTO);

ALTER TABLE PEDIDOS
ADD FOREIGN KEY (CODFORMAPAGTO) REFERENCES FORMAPAGTO(CODFORMAPAGTO);


