CREATE TABLE PED_PRODS(NROPED_PRODS INTEGER CONSTRAINT PK_PED_PRODS PRIMARY KEY,
					   NROPEDIDO INTEGER CONSTRAINT NNNROPEDIDO NOT NULL,
					   NROITEM INTEGER CONSTRAINT NNNROITEM NOT NULL,
					   CODPRODUTO VARCHAR(20) CONSTRAINT NNCODPRODUTO NOT NULL,
					   QTDE NUMERIC CONSTRAINT NNQTDE NOT NULL,
					   UN VARCHAR(2) CONSTRAINT NNUN NOT NULL, 
					   PRECO NUMERIC (10,2) CONSTRAINT NNPRECO NOT NULL,
					   PERCDESCONTO NUMERIC CONSTRAINT NNPERCDESCONTO NOT NULL,
					   VALDESCONTO NUMERIC CONSTRAINT NNVALDESCONTO NOT NULL,
					   VALTOTAL NUMERIC(10,2) CONSTRAINT NNVALTOTAL NOT NULL);
					   
ALTER TABLE PED_PRODS
ADD FOREIGN KEY (CODPRODUTO) REFERENCES PRODUTOS(CODPRODUTO);